SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION KiemTraThoiHan
(
	@MSSV NVARCHAR(10)
)
RETURNS BIT
AS
BEGIN
	DECLARE @ResultVar BIT;

	
	IF (SELECT COUNT(*) FROM HopDong WHERE MSSV = @MSSV) > 0
		SET @ResultVar  = CASE
		WHEN dbo.CheckDate((SELECT TOP 1 NgayBatDau FROM HopDong WHERE MSSV = @MSSV ORDER BY MaSo DESC),
		(SELECT TOP 1 NgayKetThuc FROM HopDong WHERE MSSV = @MSSV ORDER BY MaSo DESC)) = 1
		THEN 1
		ELSE 0
		END;
	ELSE
		SET @ResultVar = 0;


	RETURN @ResultVar

END
GO

